module.exports = [
  'barberry',
  'cascara',
  'sagrada',
  'yarrow',
  'chamomile',
  'juniper berry',
  'gravel root',
  'true unicorn root',
  'blue cohosh',
  'comfrey',
  'chickweed',
  'lobelia',
  'valerian',
  'cayenne',
  'horseradish',
  'goldenseal',
  'peruvian bark',
  'oregon grape',
  'echinacea',
  'wormwood',
  'pumpkin seeds',
  'red raspberry',
  'mullein'
];
