module.exports = [
  'Strawberry and martini tiramisu',
  'Pheasant and pear salad',
  'Champ and anchovy salad',
  'Broccoli and trout salad',
  'Longan and beetroot salad',
  'Beef and mackerel salad',
  'Shallot and wheat salad',
  'Creme fraiche and peach salad',
  'Pollack and vinegar salad',
  'Harissa and arrowroot salad',
  'Gochu jang and almond salad',
  'Bocconcini and kielbasa salad',
  'Samphire and raspberry salad',
  'Damson and angelica salad',
  'Crayfish and borscht salad',
  'Thai basil and liver salad',
  'Diavolo and savoy cabbage salad',
  'Haroset and cocoa salad',
  'Haddock and venison salad',
  'Delicata and quorn salad',
  'Limpa and thyme salad',
  'Chorizo and tia maria salad',
  'Curly kale and fettuccine salad',
  'Mizuna and jabuticaba salad',
  'Cardamom and butterbean salad',
  'Rhubarb and taleggio salad',
  'Kalnji and green cabbage salad',
  'Jujube and pork sausage meat salad',
  'Rice paper and swordfish salad',
  'Squid and caper salad',
  'Mango and persimmon salad',
  'Mustard and soy salad',
  'Turkey and basil salad',
  'Flaxseed and prawn salad',
  'Squash and marrow salad',
  'Parmesan and hp sauce salad',
  'Taramasalata and rosemary salad',
  'Italian seasoning and phyllo salad',
  'Melon and lancashire cheese salad',
  'Saffron and oaty salad',
  'Malt vinegar and chico fruit salad',
  'Raisin and pak choi salad',
  'Black pepper and orange flower water salad',
  'Jalapeno and paneer salad',
  'Tongue and blackcurrant cordial salad',
  'Soya and tempeh salad',
  'Fish sauce and corned beef salad',
  'Currant and oregano salad',
  'John dory and toenjang salad',
  'Yam and game salad',
  'Garlic powder and scotch bonnet salad',
  'Caraway and coriander salad',
  'Bean and mushroom salad',
  'Creole seasoning and juniper berry salad',
  'Peppercorn and tomato salad',
  'Guinea fowl and aioli salad',
  'Ezekiel and yuzu salad',
  'Socca and potato starch salad',
  'Gorgonzola and sunflower spread salad',
  'Nasturtium and blackcurrant salad',
  'Boysenberry and carob salad',
  'Jaggery and mint salad',
  'Cranberry and udon salad',
  'Camembert and lavender salad',
  'Jalape and sweetcorn salad',
  'Pork tenderloin and cumin seed salad',
  'Puttanesca and vacherin salad',
  'Crab and poussin salad',
  'Dill and gruyere salad',
  'Kiwi fruit and sea trout salad',
  'Feta and banana salad',
  'Emmental and canola oil salad',
  'Chilli sauce and pomegranate salad',
  'Tangerine and pork salad',
  'Elderberry and navratan salad',
  'Sea bream and fennel salad',
  'Lettuce and opossum salad',
  'Red leicester and goji berry salad',
  'Kelp and cashew salad',
  'Pastrami and celery salad',
  'Quinoa and sharon fruit salad',
  'Vermicelli and buffalo salad',
  'Mozzarella and cider vinegar salad',
  'Durian and goose salad',
  'Masa harina and cockle salad',
  'Marsala and flaxseed oil salad',
  'Squab and shrimp salad',
  'Edam and water chestnut salad',
  'Raspberry vinegar and cod salad',
  'Sausage and roquefort',
  'white cabbage',
  'Blood orange',
  'Peppermint and sage salad',
  'Eel',
  'Sole and italian dressing salad',
  'Wheat bran and cheshire cheese salad',
  'Lime peel and caramel sauce salad',
  'Chilli and breadfruit salad',
  'Hogget and truffle salad',
  'Clementine and arugula salad',
  'ensalada'
];
